language: haskell
sudo: false
# Cache .stack for build_times--
cache:
  directories:
  - $HOME/.stack
  - $HOME/.npm
before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_retry curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
install:
- travis_wait stack --skip-ghc-check setup
- travis_wait stack --skip-ghc-check install hlint
- travis_wait npm i
script:
- make hlint
- make frontend-lint
